module.exports = {
  theme: {
    extend: {
      colors: {
        "on-surface": "var(--color-on-surface, #191c1d)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #012114)",
        "background": "var(--color-background, #f8f9fa)",
        "outline": "var(--color-outline, #6f7a72)",
        "surface-variant": "var(--color-surface-variant, #e1e3e4)",
        "surface-container": "var(--color-surface-container, #edeeef)",
        "on-secondary": "var(--color-on-secondary, #ffffff)",
        "surface-container-high": "var(--color-surface-container-high, #e7e8e9)",
        "inverse-primary": "var(--color-inverse-primary, #81d8ad)",
        "tertiary": "var(--color-tertiary, #772f2c)",
        "error": "var(--color-error, #ba1a1a)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #ffb3ae)",
        "on-primary": "var(--color-on-primary, #ffffff)",
        "on-tertiary": "var(--color-on-tertiary, #ffffff)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #005236)",
        "secondary": "var(--color-secondary, #466554)",
        "on-secondary-container": "var(--color-on-secondary-container, #4c6b5a)",
        "outline-variant": "var(--color-outline-variant, #bec9c0)",
        "surface-tint": "var(--color-surface-tint, #006c49)",
        "primary-container": "var(--color-primary-container, #006c49)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #002113)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #acceba)",
        "secondary-container": "var(--color-secondary-container, #c8ebd5)",
        "primary-fixed": "var(--color-primary-fixed, #9df4c8)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #81d8ad)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #78302d)",
        "on-primary-container": "var(--color-on-primary-container, #93eabe)",
        "surface-container-low": "var(--color-surface-container-low, #f3f4f5)",
        "on-error": "var(--color-on-error, #ffffff)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #f0f1f2)",
        "on-background": "var(--color-on-background, #191c1d)",
        "surface-dim": "var(--color-surface-dim, #d9dadb)",
        "surface-bright": "var(--color-surface-bright, #f8f9fa)",
        "secondary-fixed": "var(--color-secondary-fixed, #c8ebd5)",
        "tertiary-container": "var(--color-tertiary-container, #954642)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #3e0406)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "tertiary-fixed": "var(--color-tertiary-fixed, #ffdad7)",
        "primary": "var(--color-primary, #005136)",
        "surface": "var(--color-surface, #f8f9fa)",
        "on-surface-variant": "var(--color-on-surface-variant, #3f4943)",
        "on-error-container": "var(--color-on-error-container, #93000a)",
        "inverse-surface": "var(--color-inverse-surface, #2e3132)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #2e4d3d)",
        "surface-container-highest": "var(--color-surface-container-highest, #e1e3e4)",
        "error-container": "var(--color-error-container, #ffdad6)"
      }
    }
  }
}
