module.exports = {
  theme: {
    extend: {
      colors: {
        "on-surface": "var(--color-on-surface, #0c1c16)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #253D2C)",
        "background": "var(--color-background, #f7f9f8)",
        "outline": "var(--color-outline, #2E6F40)",
        "surface-variant": "var(--color-surface-variant, #f0f4f2)",
        "surface-container": "var(--color-surface-container, #ffffff)",
        "on-secondary": "var(--color-on-secondary, #ffffff)",
        "surface-container-high": "var(--color-surface-container-high, #f5f8f6)",
        "inverse-primary": "var(--color-inverse-primary, #4DBF7D)",
        "tertiary": "var(--color-tertiary, #772f2c)",
        "error": "var(--color-error, #ba1a1a)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #ffb3ae)",
        "on-primary": "var(--color-on-primary, #ffffff)",
        "on-tertiary": "var(--color-on-tertiary, #ffffff)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #2E6F40)",
        "secondary": "var(--color-secondary, #253D2C)",
        "on-secondary-container": "var(--color-on-secondary-container, #253D2C)",
        "outline-variant": "var(--color-outline-variant, #2E6F40)",
        "surface-tint": "var(--color-surface-tint, #2E6F40)",
        "primary-container": "var(--color-primary-container, #2E6F40)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #0c1c16)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #3A483F)",
        "secondary-container": "var(--color-secondary-container, #ebf0ee)",
        "primary-fixed": "var(--color-primary-fixed, #2E6F40)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #2E6F40)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #78302d)",
        "on-primary-container": "var(--color-on-primary-container, #2E6F40)",
        "surface-container-low": "var(--color-surface-container-low, #f7f9f8)",
        "on-error": "var(--color-on-error, #ffffff)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #f7f9f8)",
        "on-background": "var(--color-on-background, #0c1c16)",
        "surface-dim": "var(--color-surface-dim, #f0f4f2)",
        "surface-bright": "var(--color-surface-bright, #f7f9f8)",
        "secondary-fixed": "var(--color-secondary-fixed, #ebf0ee)",
        "tertiary-container": "var(--color-tertiary-container, #954642)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #3e0406)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "tertiary-fixed": "var(--color-tertiary-fixed, #ffdad7)",
        "primary": "var(--color-primary, #2E6F40)",
        "surface": "var(--color-surface, #ffffff)",
        "on-surface-variant": "var(--color-on-surface-variant, #253D2C)",
        "on-error-container": "var(--color-on-error-container, #93000a)",
        "inverse-surface": "var(--color-inverse-surface, #121A15)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #253D2C)",
        "surface-container-highest": "var(--color-surface-container-highest, #f0f4f2)",
        "error-container": "var(--color-error-container, #ffdad6)"
      }
    }
  }
}
